### ISSUE TITLE
When running notebook: Error: interactive.registerCommandHandler is not a function

### ISSUE THREAD

**Issue by zo0o0ot** [ais-dotnet/Ais.Net.Notebooks#2]
I tried running both the geofenced and realtime notebook in VS Code, as well as Visual Studio.

In VS Code, I tried running the code with Javascript(.NET Interactive)

When running the following code:

```
interactive.registerCommandHandler({commandType: 'VesselPositionCommand', handle: c => {
    UpdateVesselPosition(c.command);
}});
```

I get this error:
Error: interactive.registerCommandHandler is not a function

![image](https://user-images.githubusercontent.com/876146/179892520-c70a3c33-0561-4507-bbc5-37c778c800c8.png)

In Visual Studio, the notebook cell's code is recognized as C#, so it has a different error:

![image](https://user-images.githubusercontent.com/876146/179893356-c1dd42a8-eadd-4de4-b53a-60b6983ee2b1.png)

```
(1,36): error CS1026: ) expected
(1,36): error CS1002: ; expected
(1,50): error CS1012: Too many characters in character literal
(1,73): error CS1002: ; expected
(1,73): error CS1513: } expected
(4,2): error CS1002: ; expected
(4,3): error CS7017: Member definition, statement, or end-of-file expected
```

I don't think my Visual Studio install has access to Javascript right now, so I'm willing to ignore errors there.

Is there anything I'm doing wrong? What is the best way to communicate version information of what I'm running to you?

**Comment by HowardvanRooijen** [comment]
I'll take a look. The .NET Interactive API may have changed.

**Comment by HowardvanRooijen** [comment]
I've just pushed up some changes. The .NET Interactive Kernel API had changed (your first error), and also there was a bug whereby the language setting (C# / JavaScript / HTML) of each notebook cell was lost, which is why you were getting the second error. This should work for you now.

**Comment by zo0o0ot** [comment]
When I run the new dib notebooks and load the file, things work.  That's good enough for me.  Thanks!
