### ISSUE TITLE
ais-dotnet-bing-maps-realtime.dib - FindKernel "Kernel" does not contain a definition for "FindKernel"

### ISSUE THREAD

**Issue by jeffsdata** [ais-dotnet/Ais.Net.Notebooks#3]
Hi - I tried running "ais-dotnet-bing-maps-realtime.dib", and it threw the following error:

```
var jsKernel = Kernel.Root.FindKernel("javascript");
jsKernel.RegisterCommandType<VesselPositionCommand>();
```
**Error**: (1,28): error CS1061: 'Kernel' does not contain a definition for 'FindKernel' and no accessible extension method 'FindKernel' accepting a first argument of type 'Kernel' could be found (are you missing a using directive or an assembly reference?)

I updated the "FindKernel" method to "FindKernelByName" and that seems to have worked.

**Comment by HowardvanRooijen** [comment]
Thanks for reporting that. I did have updated notebooks locally, but I hadn't pushed them up. I've just done that, so they should all be back in a working state.
